### ISSUE TITLE
3.0 doc

### ISSUE THREAD

**Issue by ko1** [fronoske/rurema_chm#1]
便利に使わせてもらっております。
3.0 のドキュメント生成はされませんか？

**Comment by fronoske** [comment]
長らく放置してしまい申し訳ありません。他の人に使われているとは思っておらず、issueもチェックしておりませんでした。。。
おまたせしましたが、本日より3.0.0のCHMビルドを開始しました。どうぞお使いください。

**Comment by fronoske** [comment]
え！？どなたかと思いきや、ささださんとは……！そんな偉人に使っていただいているとは恐縮至極です。目次などいろいろイケてなくて申し訳ないです…。

**Comment by ko1** [comment]
老人なので chm が楽なんですよね。対応いただき大変感謝しております（もしかして私しかユーザーいないんだろうか...）

**Comment by fronoske** [comment]
同じく、私も老人なので…。
Trafficを見てみると半月で20ページビューくらいでした。少なっ！
もし機会がありましたらどこかで宣伝していただけると嬉しいです(笑)。

それでは本issueはクローズさせていただきますね。もしまた何かご指摘・ご要望がありましたらお気軽にissueをお立てください。
